/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm;

import org.xtext.example.wappm.AbstractWappmRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WappmRuntimeModule extends AbstractWappmRuntimeModule {
}
