/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm;

import org.xtext.example.wappm.WappmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WappmStandaloneSetup extends WappmStandaloneSetupGenerated {
  public static void doSetup() {
    new WappmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
