/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.scoping;

import org.xtext.example.wappm.scoping.AbstractWappmScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class WappmScopeProvider extends AbstractWappmScopeProvider {
}
