/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.wappm.ui.AbstractWappmUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WappmUiModule extends AbstractWappmUiModule {
  public WappmUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
