/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WappmStandaloneSetup extends WappmStandaloneSetupGenerated {

	def static void doSetup() {
		new WappmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
