/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.wappm.wappm.ContentLayer;
import org.xtext.example.wappm.wappm.WappmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Content Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.ContentLayerImpl#getContentName <em>Content Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.ContentLayerImpl#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContentLayerImpl extends MinimalEObjectImpl.Container implements ContentLayer
{
  /**
   * The default value of the '{@link #getContentName() <em>Content Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContentName()
   * @generated
   * @ordered
   */
  protected static final String CONTENT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContentName() <em>Content Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContentName()
   * @generated
   * @ordered
   */
  protected String contentName = CONTENT_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getClasses() <em>Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClasses()
   * @generated
   * @ordered
   */
  protected EList<org.xtext.example.wappm.wappm.Class> classes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContentLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WappmPackage.Literals.CONTENT_LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getContentName()
  {
    return contentName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContentName(String newContentName)
  {
    String oldContentName = contentName;
    contentName = newContentName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.CONTENT_LAYER__CONTENT_NAME, oldContentName, contentName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<org.xtext.example.wappm.wappm.Class> getClasses()
  {
    if (classes == null)
    {
      classes = new EObjectContainmentEList<org.xtext.example.wappm.wappm.Class>(org.xtext.example.wappm.wappm.Class.class, this, WappmPackage.CONTENT_LAYER__CLASSES);
    }
    return classes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WappmPackage.CONTENT_LAYER__CLASSES:
        return ((InternalEList<?>)getClasses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WappmPackage.CONTENT_LAYER__CONTENT_NAME:
        return getContentName();
      case WappmPackage.CONTENT_LAYER__CLASSES:
        return getClasses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WappmPackage.CONTENT_LAYER__CONTENT_NAME:
        setContentName((String)newValue);
        return;
      case WappmPackage.CONTENT_LAYER__CLASSES:
        getClasses().clear();
        getClasses().addAll((Collection<? extends org.xtext.example.wappm.wappm.Class>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.CONTENT_LAYER__CONTENT_NAME:
        setContentName(CONTENT_NAME_EDEFAULT);
        return;
      case WappmPackage.CONTENT_LAYER__CLASSES:
        getClasses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.CONTENT_LAYER__CONTENT_NAME:
        return CONTENT_NAME_EDEFAULT == null ? contentName != null : !CONTENT_NAME_EDEFAULT.equals(contentName);
      case WappmPackage.CONTENT_LAYER__CLASSES:
        return classes != null && !classes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (contentName: ");
    result.append(contentName);
    result.append(')');
    return result.toString();
  }

} //ContentLayerImpl
