/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.wappm.wappm.DynamicPage;
import org.xtext.example.wappm.wappm.WappmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dynamic Page</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.DynamicPageImpl#getDisplayedClass <em>Displayed Class</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DynamicPageImpl extends PageImpl implements DynamicPage
{
  /**
   * The cached value of the '{@link #getDisplayedClass() <em>Displayed Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayedClass()
   * @generated
   * @ordered
   */
  protected org.xtext.example.wappm.wappm.Class displayedClass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DynamicPageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WappmPackage.Literals.DYNAMIC_PAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.example.wappm.wappm.Class getDisplayedClass()
  {
    if (displayedClass != null && displayedClass.eIsProxy())
    {
      InternalEObject oldDisplayedClass = (InternalEObject)displayedClass;
      displayedClass = (org.xtext.example.wappm.wappm.Class)eResolveProxy(oldDisplayedClass);
      if (displayedClass != oldDisplayedClass)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS, oldDisplayedClass, displayedClass));
      }
    }
    return displayedClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.example.wappm.wappm.Class basicGetDisplayedClass()
  {
    return displayedClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDisplayedClass(org.xtext.example.wappm.wappm.Class newDisplayedClass)
  {
    org.xtext.example.wappm.wappm.Class oldDisplayedClass = displayedClass;
    displayedClass = newDisplayedClass;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS, oldDisplayedClass, displayedClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS:
        if (resolve) return getDisplayedClass();
        return basicGetDisplayedClass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS:
        setDisplayedClass((org.xtext.example.wappm.wappm.Class)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS:
        setDisplayedClass((org.xtext.example.wappm.wappm.Class)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.DYNAMIC_PAGE__DISPLAYED_CLASS:
        return displayedClass != null;
    }
    return super.eIsSet(featureID);
  }

} //DynamicPageImpl
