/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.wappm.wappm.HypertextLayer;
import org.xtext.example.wappm.wappm.Page;
import org.xtext.example.wappm.wappm.WappmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hypertext Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.HypertextLayerImpl#getHyperName <em>Hyper Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.HypertextLayerImpl#getPages <em>Pages</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HypertextLayerImpl extends MinimalEObjectImpl.Container implements HypertextLayer
{
  /**
   * The default value of the '{@link #getHyperName() <em>Hyper Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHyperName()
   * @generated
   * @ordered
   */
  protected static final String HYPER_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHyperName() <em>Hyper Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHyperName()
   * @generated
   * @ordered
   */
  protected String hyperName = HYPER_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPages() <em>Pages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPages()
   * @generated
   * @ordered
   */
  protected EList<Page> pages;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HypertextLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WappmPackage.Literals.HYPERTEXT_LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHyperName()
  {
    return hyperName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHyperName(String newHyperName)
  {
    String oldHyperName = hyperName;
    hyperName = newHyperName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.HYPERTEXT_LAYER__HYPER_NAME, oldHyperName, hyperName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Page> getPages()
  {
    if (pages == null)
    {
      pages = new EObjectContainmentEList<Page>(Page.class, this, WappmPackage.HYPERTEXT_LAYER__PAGES);
    }
    return pages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WappmPackage.HYPERTEXT_LAYER__PAGES:
        return ((InternalEList<?>)getPages()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WappmPackage.HYPERTEXT_LAYER__HYPER_NAME:
        return getHyperName();
      case WappmPackage.HYPERTEXT_LAYER__PAGES:
        return getPages();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WappmPackage.HYPERTEXT_LAYER__HYPER_NAME:
        setHyperName((String)newValue);
        return;
      case WappmPackage.HYPERTEXT_LAYER__PAGES:
        getPages().clear();
        getPages().addAll((Collection<? extends Page>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.HYPERTEXT_LAYER__HYPER_NAME:
        setHyperName(HYPER_NAME_EDEFAULT);
        return;
      case WappmPackage.HYPERTEXT_LAYER__PAGES:
        getPages().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.HYPERTEXT_LAYER__HYPER_NAME:
        return HYPER_NAME_EDEFAULT == null ? hyperName != null : !HYPER_NAME_EDEFAULT.equals(hyperName);
      case WappmPackage.HYPERTEXT_LAYER__PAGES:
        return pages != null && !pages.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (hyperName: ");
    result.append(hyperName);
    result.append(')');
    return result.toString();
  }

} //HypertextLayerImpl
