/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.wappm.wappm.IndexPage;
import org.xtext.example.wappm.wappm.WappmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Index Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IndexPageImpl extends DynamicPageImpl implements IndexPage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IndexPageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WappmPackage.Literals.INDEX_PAGE;
  }

} //IndexPageImpl
