/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.wappm.wappm.Reference;
import org.xtext.example.wappm.wappm.WappmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.ReferenceImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.ReferenceImpl#getLowBound <em>Low Bound</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.impl.ReferenceImpl#getUpBound <em>Up Bound</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReferenceImpl extends MinimalEObjectImpl.Container implements Reference
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getLowBound() <em>Low Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLowBound()
   * @generated
   * @ordered
   */
  protected static final int LOW_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLowBound() <em>Low Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLowBound()
   * @generated
   * @ordered
   */
  protected int lowBound = LOW_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getUpBound() <em>Up Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpBound()
   * @generated
   * @ordered
   */
  protected static final int UP_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getUpBound() <em>Up Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpBound()
   * @generated
   * @ordered
   */
  protected int upBound = UP_BOUND_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WappmPackage.Literals.REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.REFERENCE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLowBound()
  {
    return lowBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLowBound(int newLowBound)
  {
    int oldLowBound = lowBound;
    lowBound = newLowBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.REFERENCE__LOW_BOUND, oldLowBound, lowBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getUpBound()
  {
    return upBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUpBound(int newUpBound)
  {
    int oldUpBound = upBound;
    upBound = newUpBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WappmPackage.REFERENCE__UP_BOUND, oldUpBound, upBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WappmPackage.REFERENCE__NAME:
        return getName();
      case WappmPackage.REFERENCE__LOW_BOUND:
        return getLowBound();
      case WappmPackage.REFERENCE__UP_BOUND:
        return getUpBound();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WappmPackage.REFERENCE__NAME:
        setName((String)newValue);
        return;
      case WappmPackage.REFERENCE__LOW_BOUND:
        setLowBound((Integer)newValue);
        return;
      case WappmPackage.REFERENCE__UP_BOUND:
        setUpBound((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.REFERENCE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case WappmPackage.REFERENCE__LOW_BOUND:
        setLowBound(LOW_BOUND_EDEFAULT);
        return;
      case WappmPackage.REFERENCE__UP_BOUND:
        setUpBound(UP_BOUND_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WappmPackage.REFERENCE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case WappmPackage.REFERENCE__LOW_BOUND:
        return lowBound != LOW_BOUND_EDEFAULT;
      case WappmPackage.REFERENCE__UP_BOUND:
        return upBound != UP_BOUND_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", lowBound: ");
    result.append(lowBound);
    result.append(", upBound: ");
    result.append(upBound);
    result.append(')');
    return result.toString();
  }

} //ReferenceImpl
