/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.wappm.ui.internal.WappmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WappmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(WappmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		WappmActivator activator = WappmActivator.getInstance();
		return activator != null ? activator.getInjector(WappmActivator.ORG_XTEXT_EXAMPLE_WAPPM_WAPPM) : null;
	}

}
