/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class WappmGrammarAccess extends AbstractGrammarElementFinder {
	
	public class WebModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.WebModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWebappKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHypertextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHypertextHypertextLayerParserRuleCall_3_0 = (RuleCall)cHypertextAssignment_3.eContents().get(0);
		private final Assignment cContentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cContentContentLayerParserRuleCall_4_0 = (RuleCall)cContentAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//WebModel:
		//	'webapp' name=ID '{'
		//	hypertext=HypertextLayer
		//	content=ContentLayer
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'webapp' name=ID '{' hypertext=HypertextLayer content=ContentLayer '}'
		public Group getGroup() { return cGroup; }
		
		//'webapp'
		public Keyword getWebappKeyword_0() { return cWebappKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//hypertext=HypertextLayer
		public Assignment getHypertextAssignment_3() { return cHypertextAssignment_3; }
		
		//HypertextLayer
		public RuleCall getHypertextHypertextLayerParserRuleCall_3_0() { return cHypertextHypertextLayerParserRuleCall_3_0; }
		
		//content=ContentLayer
		public Assignment getContentAssignment_4() { return cContentAssignment_4; }
		
		//ContentLayer
		public RuleCall getContentContentLayerParserRuleCall_4_0() { return cContentContentLayerParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class HypertextLayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.HypertextLayer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHypertextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHyperNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHyperNameIDTerminalRuleCall_1_0 = (RuleCall)cHyperNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPagesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPagesPageParserRuleCall_3_0 = (RuleCall)cPagesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//HypertextLayer:
		//	'hypertext' hyperName=ID '{'
		//	pages+=Page+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'hypertext' hyperName=ID '{' pages+=Page+ '}'
		public Group getGroup() { return cGroup; }
		
		//'hypertext'
		public Keyword getHypertextKeyword_0() { return cHypertextKeyword_0; }
		
		//hyperName=ID
		public Assignment getHyperNameAssignment_1() { return cHyperNameAssignment_1; }
		
		//ID
		public RuleCall getHyperNameIDTerminalRuleCall_1_0() { return cHyperNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//pages+=Page+
		public Assignment getPagesAssignment_3() { return cPagesAssignment_3; }
		
		//Page
		public RuleCall getPagesPageParserRuleCall_3_0() { return cPagesPageParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.Page");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStaticPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDynamicPageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Page:
		//	StaticPage | DynamicPage;
		@Override public ParserRule getRule() { return rule; }
		
		//StaticPage | DynamicPage
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StaticPage
		public RuleCall getStaticPageParserRuleCall_0() { return cStaticPageParserRuleCall_0; }
		
		//DynamicPage
		public RuleCall getDynamicPageParserRuleCall_1() { return cDynamicPageParserRuleCall_1; }
	}
	public class StaticPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.StaticPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStaticKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPathKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUrlAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUrlURLParserRuleCall_4_0 = (RuleCall)cUrlAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinksKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLinksAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLinksLinkParserRuleCall_5_2_0 = (RuleCall)cLinksAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLinksAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLinksLinkParserRuleCall_5_3_1_0 = (RuleCall)cLinksAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StaticPage:
		//	'static' name=ID
		//	'{'
		//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'static' name=ID '{' 'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'static'
		public Keyword getStaticKeyword_0() { return cStaticKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'path'
		public Keyword getPathKeyword_3() { return cPathKeyword_3; }
		
		//url=URL
		public Assignment getUrlAssignment_4() { return cUrlAssignment_4; }
		
		//URL
		public RuleCall getUrlURLParserRuleCall_4_0() { return cUrlURLParserRuleCall_4_0; }
		
		//('links' '{' links+=Link ("," links+=Link)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'links'
		public Keyword getLinksKeyword_5_0() { return cLinksKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//links+=Link
		public Assignment getLinksAssignment_5_2() { return cLinksAssignment_5_2; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_5_2_0() { return cLinksLinkParserRuleCall_5_2_0; }
		
		//("," links+=Link)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//links+=Link
		public Assignment getLinksAssignment_5_3_1() { return cLinksAssignment_5_3_1; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_5_3_1_0() { return cLinksLinkParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DynamicPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.DynamicPage");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIndexPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDetailPageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//DynamicPage:
		//	IndexPage | DetailPage;
		@Override public ParserRule getRule() { return rule; }
		
		//IndexPage | DetailPage
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IndexPage
		public RuleCall getIndexPageParserRuleCall_0() { return cIndexPageParserRuleCall_0; }
		
		//DetailPage
		public RuleCall getDetailPageParserRuleCall_1() { return cDetailPageParserRuleCall_1; }
	}
	public class DetailPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.DetailPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDetailKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cUsesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDisplayedClassAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cDisplayedClassClassCrossReference_3_0 = (CrossReference)cDisplayedClassAssignment_3.eContents().get(0);
		private final RuleCall cDisplayedClassClassIDTerminalRuleCall_3_0_1 = (RuleCall)cDisplayedClassClassCrossReference_3_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cPathKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUrlAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUrlURLParserRuleCall_6_0 = (RuleCall)cUrlAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLinksKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cLinksAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cLinksLinkParserRuleCall_7_2_0 = (RuleCall)cLinksAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cLinksAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cLinksLinkParserRuleCall_7_3_1_0 = (RuleCall)cLinksAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//DetailPage:
		//	'detail' name=ID 'uses' displayedClass=[Class]
		//	'{'
		//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'detail' name=ID 'uses' displayedClass=[Class] '{' 'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'detail'
		public Keyword getDetailKeyword_0() { return cDetailKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'uses'
		public Keyword getUsesKeyword_2() { return cUsesKeyword_2; }
		
		//displayedClass=[Class]
		public Assignment getDisplayedClassAssignment_3() { return cDisplayedClassAssignment_3; }
		
		//[Class]
		public CrossReference getDisplayedClassClassCrossReference_3_0() { return cDisplayedClassClassCrossReference_3_0; }
		
		//ID
		public RuleCall getDisplayedClassClassIDTerminalRuleCall_3_0_1() { return cDisplayedClassClassIDTerminalRuleCall_3_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'path'
		public Keyword getPathKeyword_5() { return cPathKeyword_5; }
		
		//url=URL
		public Assignment getUrlAssignment_6() { return cUrlAssignment_6; }
		
		//URL
		public RuleCall getUrlURLParserRuleCall_6_0() { return cUrlURLParserRuleCall_6_0; }
		
		//('links' '{' links+=Link ("," links+=Link)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'links'
		public Keyword getLinksKeyword_7_0() { return cLinksKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//links+=Link
		public Assignment getLinksAssignment_7_2() { return cLinksAssignment_7_2; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_7_2_0() { return cLinksLinkParserRuleCall_7_2_0; }
		
		//("," links+=Link)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//links+=Link
		public Assignment getLinksAssignment_7_3_1() { return cLinksAssignment_7_3_1; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_7_3_1_0() { return cLinksLinkParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class IndexPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.IndexPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIndexKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cUsesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDisplayedClassAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cDisplayedClassClassCrossReference_3_0 = (CrossReference)cDisplayedClassAssignment_3.eContents().get(0);
		private final RuleCall cDisplayedClassClassIDTerminalRuleCall_3_0_1 = (RuleCall)cDisplayedClassClassCrossReference_3_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cPathKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUrlAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUrlURLParserRuleCall_6_0 = (RuleCall)cUrlAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLinksKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cLinksAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cLinksLinkParserRuleCall_7_2_0 = (RuleCall)cLinksAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cLinksAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cLinksLinkParserRuleCall_7_3_1_0 = (RuleCall)cLinksAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//IndexPage:
		//	'index' name=ID 'uses' displayedClass=[Class]
		//	'{'
		//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'index' name=ID 'uses' displayedClass=[Class] '{' 'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'index'
		public Keyword getIndexKeyword_0() { return cIndexKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'uses'
		public Keyword getUsesKeyword_2() { return cUsesKeyword_2; }
		
		//displayedClass=[Class]
		public Assignment getDisplayedClassAssignment_3() { return cDisplayedClassAssignment_3; }
		
		//[Class]
		public CrossReference getDisplayedClassClassCrossReference_3_0() { return cDisplayedClassClassCrossReference_3_0; }
		
		//ID
		public RuleCall getDisplayedClassClassIDTerminalRuleCall_3_0_1() { return cDisplayedClassClassIDTerminalRuleCall_3_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'path'
		public Keyword getPathKeyword_5() { return cPathKeyword_5; }
		
		//url=URL
		public Assignment getUrlAssignment_6() { return cUrlAssignment_6; }
		
		//URL
		public RuleCall getUrlURLParserRuleCall_6_0() { return cUrlURLParserRuleCall_6_0; }
		
		//('links' '{' links+=Link ("," links+=Link)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'links'
		public Keyword getLinksKeyword_7_0() { return cLinksKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//links+=Link
		public Assignment getLinksAssignment_7_2() { return cLinksAssignment_7_2; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_7_2_0() { return cLinksLinkParserRuleCall_7_2_0; }
		
		//("," links+=Link)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//links+=Link
		public Assignment getLinksAssignment_7_3_1() { return cLinksAssignment_7_3_1; }
		
		//Link
		public RuleCall getLinksLinkParserRuleCall_7_3_1_0() { return cLinksLinkParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class LinkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.Link");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLinkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPagePageCrossReference_3_0 = (CrossReference)cPageAssignment_3.eContents().get(0);
		private final RuleCall cPagePageIDTerminalRuleCall_3_0_1 = (RuleCall)cPagePageCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Link:
		//	'link' '{'
		//	'page' page=[Page]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'link' '{' 'page' page=[Page] '}'
		public Group getGroup() { return cGroup; }
		
		//'link'
		public Keyword getLinkKeyword_0() { return cLinkKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'page'
		public Keyword getPageKeyword_2() { return cPageKeyword_2; }
		
		//page=[Page]
		public Assignment getPageAssignment_3() { return cPageAssignment_3; }
		
		//[Page]
		public CrossReference getPagePageCrossReference_3_0() { return cPagePageCrossReference_3_0; }
		
		//ID
		public RuleCall getPagePageIDTerminalRuleCall_3_0_1() { return cPagePageIDTerminalRuleCall_3_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ContentLayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.ContentLayer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cContentNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cContentNameIDTerminalRuleCall_1_0 = (RuleCall)cContentNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cClassesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cClassesClassParserRuleCall_3_0 = (RuleCall)cClassesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ContentLayer:
		//	'content' contentName=ID '{'
		//	classes+=Class+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'content' contentName=ID '{' classes+=Class+ '}'
		public Group getGroup() { return cGroup; }
		
		//'content'
		public Keyword getContentKeyword_0() { return cContentKeyword_0; }
		
		//contentName=ID
		public Assignment getContentNameAssignment_1() { return cContentNameAssignment_1; }
		
		//ID
		public RuleCall getContentNameIDTerminalRuleCall_1_0() { return cContentNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//classes+=Class+
		public Assignment getClassesAssignment_3() { return cClassesAssignment_3; }
		
		//Class
		public RuleCall getClassesClassParserRuleCall_3_0() { return cClassesClassParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttributesAttributeParserRuleCall_3_0 = (RuleCall)cAttributesAssignment_3.eContents().get(0);
		private final Keyword cUniqueIdentifierKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUniqueIdentifierAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cUniqueIdentifierAttributeCrossReference_5_0 = (CrossReference)cUniqueIdentifierAssignment_5.eContents().get(0);
		private final RuleCall cUniqueIdentifierAttributeIDTerminalRuleCall_5_0_1 = (RuleCall)cUniqueIdentifierAttributeCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Class:
		//	'class' name=ID '{'
		//	attributes+=Attribute+
		//	'uniqueIdentifier' uniqueIdentifier=[Attribute]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'class' name=ID '{' attributes+=Attribute+ 'uniqueIdentifier' uniqueIdentifier=[Attribute] '}'
		public Group getGroup() { return cGroup; }
		
		//'class'
		public Keyword getClassKeyword_0() { return cClassKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//attributes+=Attribute+
		public Assignment getAttributesAssignment_3() { return cAttributesAssignment_3; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_3_0() { return cAttributesAttributeParserRuleCall_3_0; }
		
		//'uniqueIdentifier'
		public Keyword getUniqueIdentifierKeyword_4() { return cUniqueIdentifierKeyword_4; }
		
		//uniqueIdentifier=[Attribute]
		public Assignment getUniqueIdentifierAssignment_5() { return cUniqueIdentifierAssignment_5; }
		
		//[Attribute]
		public CrossReference getUniqueIdentifierAttributeCrossReference_5_0() { return cUniqueIdentifierAttributeCrossReference_5_0; }
		
		//ID
		public RuleCall getUniqueIdentifierAttributeIDTerminalRuleCall_5_0_1() { return cUniqueIdentifierAttributeIDTerminalRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttrKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeAppTypesEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		
		//Attribute:
		//	'attr' name=ID ':' type=AppTypes;
		@Override public ParserRule getRule() { return rule; }
		
		//'attr' name=ID ':' type=AppTypes
		public Group getGroup() { return cGroup; }
		
		//'attr'
		public Keyword getAttrKeyword_0() { return cAttrKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=AppTypes
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//AppTypes
		public RuleCall getTypeAppTypesEnumRuleCall_3_0() { return cTypeAppTypesEnumRuleCall_3_0; }
	}
	public class URLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.URL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cURLAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cSolidusKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cSolidusKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1_1 = (Alternatives)cGroup_1_1.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_1_1_0 = (RuleCall)cAlternatives_1_1_1.eContents().get(0);
		private final Assignment cAdditionAssignment_1_1_1_1 = (Assignment)cAlternatives_1_1_1.eContents().get(1);
		private final RuleCall cAdditionURL_ADDITIONParserRuleCall_1_1_1_1_0 = (RuleCall)cAdditionAssignment_1_1_1_1.eContents().get(0);
		
		//URL:
		//	{URL} ('/' | ('/' (ID | addition+=URL_ADDITION))*);
		@Override public ParserRule getRule() { return rule; }
		
		//{URL} ('/' | ('/' (ID | addition+=URL_ADDITION))*)
		public Group getGroup() { return cGroup; }
		
		//{URL}
		public Action getURLAction_0() { return cURLAction_0; }
		
		//// object instantiation
		//'/' | ('/' (ID | addition+=URL_ADDITION))*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0() { return cSolidusKeyword_1_0; }
		
		//('/' (ID | addition+=URL_ADDITION))*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'/'
		public Keyword getSolidusKeyword_1_1_0() { return cSolidusKeyword_1_1_0; }
		
		//ID | addition+=URL_ADDITION
		public Alternatives getAlternatives_1_1_1() { return cAlternatives_1_1_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1_1_0() { return cIDTerminalRuleCall_1_1_1_0; }
		
		//addition+=URL_ADDITION
		public Assignment getAdditionAssignment_1_1_1_1() { return cAdditionAssignment_1_1_1_1; }
		
		//URL_ADDITION
		public RuleCall getAdditionURL_ADDITIONParserRuleCall_1_1_1_1_0() { return cAdditionURL_ADDITIONParserRuleCall_1_1_1_1_0; }
	}
	public class URL_ADDITIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.URL_ADDITION");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColonKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cQuestionMarkKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		
		//URL_ADDITION:
		//	':' name=ID | '?' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//':' name=ID | '?' name=ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//':' name=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//':'
		public Keyword getColonKeyword_0_0() { return cColonKeyword_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }
		
		//'?' name=ID
		public Group getGroup_1() { return cGroup_1; }
		
		//'?'
		public Keyword getQuestionMarkKeyword_1_0() { return cQuestionMarkKeyword_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }
	}
	
	public class AppTypesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.wappm.Wappm.AppTypes");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntegerIntegerKeyword_1_0 = (Keyword)cIntegerEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFloatFloatKeyword_2_0 = (Keyword)cFloatEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDoubleDoubleKeyword_3_0 = (Keyword)cDoubleEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBooleanBooleanKeyword_4_0 = (Keyword)cBooleanEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum AppTypes:
		//	String | Integer | Float | Double | Boolean;
		public EnumRule getRule() { return rule; }
		
		//String | Integer | Float | Double | Boolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//"String"
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//Integer
		public EnumLiteralDeclaration getIntegerEnumLiteralDeclaration_1() { return cIntegerEnumLiteralDeclaration_1; }
		
		//"Integer"
		public Keyword getIntegerIntegerKeyword_1_0() { return cIntegerIntegerKeyword_1_0; }
		
		//Float
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_2() { return cFloatEnumLiteralDeclaration_2; }
		
		//"Float"
		public Keyword getFloatFloatKeyword_2_0() { return cFloatFloatKeyword_2_0; }
		
		//Double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_3() { return cDoubleEnumLiteralDeclaration_3; }
		
		//"Double"
		public Keyword getDoubleDoubleKeyword_3_0() { return cDoubleDoubleKeyword_3_0; }
		
		//Boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_4() { return cBooleanEnumLiteralDeclaration_4; }
		
		//"Boolean"
		public Keyword getBooleanBooleanKeyword_4_0() { return cBooleanBooleanKeyword_4_0; }
	}
	
	private final WebModelElements pWebModel;
	private final HypertextLayerElements pHypertextLayer;
	private final PageElements pPage;
	private final StaticPageElements pStaticPage;
	private final DynamicPageElements pDynamicPage;
	private final DetailPageElements pDetailPage;
	private final IndexPageElements pIndexPage;
	private final LinkElements pLink;
	private final ContentLayerElements pContentLayer;
	private final ClassElements pClass;
	private final AttributeElements pAttribute;
	private final AppTypesElements eAppTypes;
	private final URLElements pURL;
	private final URL_ADDITIONElements pURL_ADDITION;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WappmGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWebModel = new WebModelElements();
		this.pHypertextLayer = new HypertextLayerElements();
		this.pPage = new PageElements();
		this.pStaticPage = new StaticPageElements();
		this.pDynamicPage = new DynamicPageElements();
		this.pDetailPage = new DetailPageElements();
		this.pIndexPage = new IndexPageElements();
		this.pLink = new LinkElements();
		this.pContentLayer = new ContentLayerElements();
		this.pClass = new ClassElements();
		this.pAttribute = new AttributeElements();
		this.eAppTypes = new AppTypesElements();
		this.pURL = new URLElements();
		this.pURL_ADDITION = new URL_ADDITIONElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.wappm.Wappm".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//WebModel:
	//	'webapp' name=ID '{'
	//	hypertext=HypertextLayer
	//	content=ContentLayer
	//	'}';
	public WebModelElements getWebModelAccess() {
		return pWebModel;
	}
	
	public ParserRule getWebModelRule() {
		return getWebModelAccess().getRule();
	}
	
	//HypertextLayer:
	//	'hypertext' hyperName=ID '{'
	//	pages+=Page+
	//	'}';
	public HypertextLayerElements getHypertextLayerAccess() {
		return pHypertextLayer;
	}
	
	public ParserRule getHypertextLayerRule() {
		return getHypertextLayerAccess().getRule();
	}
	
	//Page:
	//	StaticPage | DynamicPage;
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}
	
	//StaticPage:
	//	'static' name=ID
	//	'{'
	//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
	//	'}';
	public StaticPageElements getStaticPageAccess() {
		return pStaticPage;
	}
	
	public ParserRule getStaticPageRule() {
		return getStaticPageAccess().getRule();
	}
	
	//DynamicPage:
	//	IndexPage | DetailPage;
	public DynamicPageElements getDynamicPageAccess() {
		return pDynamicPage;
	}
	
	public ParserRule getDynamicPageRule() {
		return getDynamicPageAccess().getRule();
	}
	
	//DetailPage:
	//	'detail' name=ID 'uses' displayedClass=[Class]
	//	'{'
	//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
	//	'}';
	public DetailPageElements getDetailPageAccess() {
		return pDetailPage;
	}
	
	public ParserRule getDetailPageRule() {
		return getDetailPageAccess().getRule();
	}
	
	//IndexPage:
	//	'index' name=ID 'uses' displayedClass=[Class]
	//	'{'
	//	'path' url=URL ('links' '{' links+=Link ("," links+=Link)* '}')?
	//	'}';
	public IndexPageElements getIndexPageAccess() {
		return pIndexPage;
	}
	
	public ParserRule getIndexPageRule() {
		return getIndexPageAccess().getRule();
	}
	
	//Link:
	//	'link' '{'
	//	'page' page=[Page]
	//	'}';
	public LinkElements getLinkAccess() {
		return pLink;
	}
	
	public ParserRule getLinkRule() {
		return getLinkAccess().getRule();
	}
	
	//ContentLayer:
	//	'content' contentName=ID '{'
	//	classes+=Class+
	//	'}';
	public ContentLayerElements getContentLayerAccess() {
		return pContentLayer;
	}
	
	public ParserRule getContentLayerRule() {
		return getContentLayerAccess().getRule();
	}
	
	//Class:
	//	'class' name=ID '{'
	//	attributes+=Attribute+
	//	'uniqueIdentifier' uniqueIdentifier=[Attribute]
	//	'}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//Attribute:
	//	'attr' name=ID ':' type=AppTypes;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//enum AppTypes:
	//	String | Integer | Float | Double | Boolean;
	public AppTypesElements getAppTypesAccess() {
		return eAppTypes;
	}
	
	public EnumRule getAppTypesRule() {
		return getAppTypesAccess().getRule();
	}
	
	//URL:
	//	{URL} ('/' | ('/' (ID | addition+=URL_ADDITION))*);
	public URLElements getURLAccess() {
		return pURL;
	}
	
	public ParserRule getURLRule() {
		return getURLAccess().getRule();
	}
	
	//URL_ADDITION:
	//	':' name=ID | '?' name=ID;
	public URL_ADDITIONElements getURL_ADDITIONAccess() {
		return pURL_ADDITION;
	}
	
	public ParserRule getURL_ADDITIONRule() {
		return getURL_ADDITIONAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
