/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.wappm.WappmRuntimeModule;
import org.xtext.example.wappm.WappmStandaloneSetup;
import org.xtext.example.wappm.ide.WappmIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WappmIdeSetup extends WappmStandaloneSetup {
  @Override
  public Injector createInjector() {
    WappmRuntimeModule _wappmRuntimeModule = new WappmRuntimeModule();
    WappmIdeModule _wappmIdeModule = new WappmIdeModule();
    return Guice.createInjector(Modules2.mixin(_wappmRuntimeModule, _wappmIdeModule));
  }
}
