/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ide;

import org.xtext.example.wappm.ide.AbstractWappmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WappmIdeModule extends AbstractWappmIdeModule {
}
