/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.wappm.ui.internal.WappmActivator;

public class WappmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WappmActivator.getInstance().getInjector("org.xtext.example.wappm.Wappm");
	}

}
