/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.Class#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.Class#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.Class#getUniqueIdentifier <em>Unique Identifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.Class#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.wappm.wappm.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.example.wappm.wappm.WappmPackage#getClass_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Unique Identifier</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unique Identifier</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique Identifier</em>' reference.
   * @see #setUniqueIdentifier(Attribute)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getClass_UniqueIdentifier()
   * @model
   * @generated
   */
  Attribute getUniqueIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.Class#getUniqueIdentifier <em>Unique Identifier</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unique Identifier</em>' reference.
   * @see #getUniqueIdentifier()
   * @generated
   */
  void setUniqueIdentifier(Attribute value);

} // Class
