/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.ContentLayer#getContentName <em>Content Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.ContentLayer#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getContentLayer()
 * @model
 * @generated
 */
public interface ContentLayer extends EObject
{
  /**
   * Returns the value of the '<em><b>Content Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content Name</em>' attribute.
   * @see #setContentName(String)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getContentLayer_ContentName()
   * @model
   * @generated
   */
  String getContentName();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.ContentLayer#getContentName <em>Content Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content Name</em>' attribute.
   * @see #getContentName()
   * @generated
   */
  void setContentName(String value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.wappm.wappm.WebClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see org.xtext.example.wappm.wappm.WappmPackage#getContentLayer_Classes()
   * @model containment="true"
   * @generated
   */
  EList<WebClass> getClasses();

} // ContentLayer
