/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Detail Page</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getDetailPage()
 * @model
 * @generated
 */
public interface DetailPage extends DynamicPage
{
} // DetailPage
