/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dynamic Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.DynamicPage#getDisplayedClass <em>Displayed Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getDynamicPage()
 * @model
 * @generated
 */
public interface DynamicPage extends Page
{
  /**
   * Returns the value of the '<em><b>Displayed Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Displayed Class</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Displayed Class</em>' reference.
   * @see #setDisplayedClass(WebClass)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getDynamicPage_DisplayedClass()
   * @model
   * @generated
   */
  WebClass getDisplayedClass();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.DynamicPage#getDisplayedClass <em>Displayed Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Displayed Class</em>' reference.
   * @see #getDisplayedClass()
   * @generated
   */
  void setDisplayedClass(WebClass value);

} // DynamicPage
