/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.Reference#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.Reference#getLowBound <em>Low Bound</em>}</li>
 *   <li>{@link org.xtext.example.wappm.wappm.Reference#getUpBound <em>Up Bound</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getReference()
 * @model
 * @generated
 */
public interface Reference extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getReference_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.Reference#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Low Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Low Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Low Bound</em>' attribute.
   * @see #setLowBound(int)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getReference_LowBound()
   * @model
   * @generated
   */
  int getLowBound();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.Reference#getLowBound <em>Low Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Low Bound</em>' attribute.
   * @see #getLowBound()
   * @generated
   */
  void setLowBound(int value);

  /**
   * Returns the value of the '<em><b>Up Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Up Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Up Bound</em>' attribute.
   * @see #setUpBound(int)
   * @see org.xtext.example.wappm.wappm.WappmPackage#getReference_UpBound()
   * @model
   * @generated
   */
  int getUpBound();

  /**
   * Sets the value of the '{@link org.xtext.example.wappm.wappm.Reference#getUpBound <em>Up Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Up Bound</em>' attribute.
   * @see #getUpBound()
   * @generated
   */
  void setUpBound(int value);

} // Reference
