/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.wappm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>URL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.wappm.wappm.URL#getAddition <em>Addition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.wappm.wappm.WappmPackage#getURL()
 * @model
 * @generated
 */
public interface URL extends EObject
{
  /**
   * Returns the value of the '<em><b>Addition</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.wappm.wappm.URL_ADDITION}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Addition</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addition</em>' containment reference list.
   * @see org.xtext.example.wappm.wappm.WappmPackage#getURL_Addition()
   * @model containment="true"
   * @generated
   */
  EList<URL_ADDITION> getAddition();

} // URL
