/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.wappm.ui.contentassist;

import org.xtext.example.wappm.ui.contentassist.AbstractWappmProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WappmProposalProvider extends AbstractWappmProposalProvider {
}
